### ISSUE TITLE
No menubar icon on Yosemite

### ISSUE THREAD

**Issue by montogeek** [auth0/sharelock-osx#1]
There is not menubar icon on Yosemite:
![out](https://cloud.githubusercontent.com/assets/1002461/6385896/7a758436-bd3e-11e4-81c4-1447ddd1d855.gif)

**Comment by paulyoung** [comment]
This is no doubt the same issue as paulyoung/Statusfy#13.

**Comment by montogeek** [comment]
Fixed on the lastest version.
